version: '3.9'


services:
  db:
    image: mysql:5.7
    container_name: knockbank-db
    environment:
      MYSQL_DATABASE: 'knock_bank_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql-db:/var/lib/mysql

  api:
    container_name: knockbank-api
    build: 
      context: ./server
    depends_on:
      - db

  web:
    container_name: knockbank-web
    build: 
      context: ./client
    depends_on:
      - api

  proxy:
    container_name: nginx-proxy
    restart: always
    build: 
      context: ./deploy
    depends_on:
      - web
    ports:
      - "80:80"

volumes:
  mysql-db: