services:
  db:
    image: mysql:8.3.0
    container_name: knockbank-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'knock_bank_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql-db:/var/lib/mysql

  api:
    container_name: knockbank-api
    ports:
      - "8000:8000"
    build: 
      context: ./server
    environment:
      TOKEN_SECRET: 'supersecretkey'
      SHOW_SQL: false
      SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://admin:admin@db:3306/knock_bank_db'
    depends_on:
      - db

  web:
    container_name: knockbank-web
    ports:
      - "3000:3000"
    build: 
      context: ./client
      args:
        NEXT_PUBLIC_API_URL: 'http://localhost:8000/api'
    depends_on:
      - api

volumes:
  mysql-db: