name: Continuos Integration - CI

on: 
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # API - Build
      - name: Using Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.12"
      
      # Install UV
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Dependencies
        run: |
          cd server
          uv sync

      # API - Tests
      - name: Running Tests
        run: |
          cd server
          uv run pytest
        env:
          TOKEN_SECRET: testkey
          SQLALCHEMY_DATABASE_URI: 'sqlite:///:memory:'
      
      # Web - Build
      - name: Using NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: "20.9.0"
          
      - name: Instaling Yarn
        run: npm install -g yarn

      - name: Building NextJS
        run: |
          cd client
          yarn install
          yarn build
        env:
          NEXT_PUBLIC_API_URL: https//any_url.com

      # Web - Tests
      # Work In Progress

      # Login Dockerhub
      # - name: Login Dockerhub
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      # # API - Docker Image
      # - name: Build API Docker Image 
      #   run: |
      #     cd server
      #     docker build . -t davilucciola/knockbank-api

      # - name: Push API Docker Image
      #   run: docker push davilucciola/knockbank-api:latest
      
      # Web - Docker Image
      # - name: Build Web Docker Image
      #   run: |
      #     cd client
      #     docker build . -t davilucciola/knockbank-web
      
      # - name: Push Web Docker Image
      #   run: docker push davilucciola/knockbank-web:latest