name: Continuos Integration (Test)

on: 
  push:
    branches: [dev]

  pull_request:
      branches: [dev]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Building API
      - name: Using Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          cd server
          pip install --upgrade pip
          pip install --no-cache-dir poetry
          poetry config virtualenvs.create false
          poetry install

      # API Tests
      - name: Running Tests
        run: |
          cd server
          poetry run pytest